version: "3.9"

services:
  database:
    image: postgres
    container_name: database_houseclean
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=house
      - POSTGRES_PASSWORD=houseclean
      - POSTGRES_DB=houseclean
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: houseclean
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/user/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local